language: python
python:
  - "3.6"
install:
  - pip install pycodestyle
  - pip install pylint
  - pip install pylint_runner
script:
  - pycodestyle --version
  - pycodestyle . --ignore=E402,E501,W503,W504
  - python -m pylint --version
  - pylint_runner --version
  - pylint_runner
